### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by JamieCruwys**

### CODE REVIEW

**Comment by yshrsmz** [comment]
Thanks, but it's not a typo
https://dictionary.cambridge.org/ja/dictionary/english/registrar

**Comment by JamieCruwys** [comment]
I'm referring to the method signature which is:
`Unregister registerEventListener(Activity, KeyboardVisibilityEventListener)`

as per
https://github.com/yshrsmz/KeyboardVisibilityEvent/pull/18/files#diff-e1569f06df099ff47aeaafb817691cc9R23

vs `Unregistrar` which is in the changelog

cc/ @yshrsmz

**Comment by yshrsmz** [comment]
ohh, so you are saying that in that moment it was `Unregister`, right?

**Comment by yshrsmz** [comment]
But even so, `Unregister` has never been appeared on released API. 
I think it confuses people if I reference something that is not present in that release.

https://github.com/yshrsmz/KeyboardVisibilityEvent/blob/v2.1.0/keyboardvisibilityevent/src/main/java/net/yslibrary/android/keyboardvisibilityevent/KeyboardVisibilityEvent.java

Maybe I should've added link to the commit I renamed that class.

**Pull request closed without merging**
